@preconcurrency import Foundation

/// Handles backend communication with the Private Cloud LLM Brain
public actor NetworkManager {
    public static let shared = NetworkManager()
    
    private init() {}
    
    /// Uploads an audio file URL to the cloud asynchronously
    /// Can be triggered via App Intents or Background Tasks
    public func uploadAudioFile(at url: URL, location: String? = nil) async throws -> Bool {
        guard let apiURL = URL(string: APIConfig.baseURL + APIConfig.Endpoints.uploadAudio) else {
            throw URLError(.badURL)
        }
        
        var request = URLRequest(url: apiURL)
        request.httpMethod = "POST"
        request.setValue("Bearer \\(APIConfig.apiKey)", forHTTPHeaderField: "Authorization")
        
        let audioData = try Data(contentsOf: url)
        let base64String = audioData.base64EncodedString()
        
        // Construct the request matching our protocol
        let payload = AudioUploadRequest(
            timestamp: Date(),
            base64Audio: base64String,
            optionalTranscription: nil,
            location: location
        )
        
        let encoder = JSONEncoder()
        request.setValue("application/json", forHTTPHeaderField: "Content-Type")
        request.httpBody = try encoder.encode(payload)
        
        // Execute network request
        let (data, response) = try await withCheckedThrowingContinuation { (continuation: CheckedContinuation<(Data, URLResponse), Error>) in
            let task = URLSession.shared.dataTask(with: request) { d, r, e in
                if let error = e {
                    continuation.resume(throwing: error)
                } else if let d = d, let r = r {
                    continuation.resume(returning: (d, r))
                } else {
                    continuation.resume(throwing: URLError(.badServerResponse))
                }
            }
            task.resume()
        }
        
        guard let httpResponse = response as? HTTPURLResponse,
              (200...299).contains(httpResponse.statusCode) else {
            print("Upload failed with response: \\(response)")
            return false
        }
        
        print("Successfully uploaded \\(url.lastPathComponent) to Cloud Brain. \\(data.count) bytes returned.")
        return true
    }
    
    /// Fetches the synthesized Daily Report generated by the LLM
    public func fetchDailyReport() async throws -> DailyReport {
        guard let apiURL = URL(string: APIConfig.baseURL + APIConfig.Endpoints.getDailyReport) else {
            throw URLError(.badURL)
        }
        
        var request = URLRequest(url: apiURL)
        request.httpMethod = "GET"
        request.setValue("Bearer \\(APIConfig.apiKey)", forHTTPHeaderField: "Authorization")
        
        let (data, response) = try await withCheckedThrowingContinuation { (continuation: CheckedContinuation<(Data, URLResponse), Error>) in
            let task = URLSession.shared.dataTask(with: request) { d, r, e in
                if let error = e {
                    continuation.resume(throwing: error)
                } else if let d = d, let r = r {
                    continuation.resume(returning: (d, r))
                } else {
                    continuation.resume(throwing: URLError(.badServerResponse))
                }
            }
            task.resume()
        }
        
        guard let httpResponse = response as? HTTPURLResponse,
              (200...299).contains(httpResponse.statusCode) else {
            throw URLError(.badServerResponse)
        }
        
        // Decode out of the actor
        let decoder = JSONDecoder()
        decoder.dateDecodingStrategy = .iso8601
        
        return try decoder.decode(DailyReport.self, from: data)
    }
}
